### ISSUE TITLE
Katacoda Support - Missing Environment

### ISSUE THREAD

**Issue by BenHall** [so0k/katacoda-scenarios#1]
Hi Vincent,

Great to see you looking at Katacoda scenarios. Sorry you encountered an error with the Terraform environment. Previously, this isn't something we had made available to the community. 

However, I've made the change and the environment is now accessible. 

I look forward to learning from what you create on Katacoda. Please let me know if you have any other questions and if the environment is working correctly.

Ben

**Comment by so0k** [comment]
thanks, I 've been running terraform workshops for the community for a while and use AWS instances with temporary AWS Credentials. 

I considered Katacoda but not sure if exercises make sense without an actual cloud API to play with.. so I abandoned it. 

looking at it again now for concourse

closing this issue for now, I'll remove the terraform scenario as it I will most likely not proceed with it and keep using https://github.com/so0k/terraform-workshop

**Comment by BenHall** [comment]
Thanks for the update. We do have cloud API integrations, please email us for more information if you are interested.
